name: subscription_management
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dio: ^5.4.1
  flutter_screenutil: ^5.6.1
  equatable: ^2.0.5
  get_it: ^7.6.0
  bloc_test: ^9.1.4
  test_cov_console: ^0.2.2
  mocktail: ^1.0.0
  flutter_native_splash: ^2.3.5
  intl: 0.20.2
  lottie: ^2.6.0
  json_annotation: ^4.8.1
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  firebase_database: ^11.2.0
  firebase_app_check: ^0.3.2+4
  dartz: ^0.10.1
  cloud_firestore: ^5.3.0
  firebase_core: ^3.12.1
  image_picker: ^1.0.7
  shared_preferences: ^2.3.5
  cached_network_image: ^3.4.1
  auto_route: ^10.0.1
  string_validator: ^1.1.0
  doso: ^1.0.0

  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  auto_route_generator: ^10.0.1


  flutter_lints: ^3.0.0


flutter_native_splash:
  color: "#E4E4ED"
  image: assets/images/subscription_management_logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  generate: true

  
  assets:
   - assets/images/
   - assets/logos/
   - assets/streaming_list.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
